### ISSUE TITLE
Question about @ObservableProperty decorator

### ISSUE THREAD

**Issue by bearoutthere** [NativeScript/template-master-detail-ts#67]
Hello,
i'm new to NativeScript and TypeScript and just working through the example templates.  I keep seeing code using a decorator like this:
`@ObservableProperty() car: Car;`

I looked at the decorator function definition but still can't quite understand what's it's for.  Would anybody please explain why this pattern is used.
Thanks in advance.

**Comment by manoldonev** [comment]
@bearoutthere check this discussion here https://stackoverflow.com/questions/43311582/nativescript-class-implementing-observables-default-setter-behaviour/43312030 that is the inspiration for the ObservableProperty decorator.

**Comment by bearoutthere** [comment]
Got it.  A great solution and now that i've been actually building models even with a moderate number of properties i realize how much work this decorator saves.  It's also great to use the simple . notation for properties `this.propertyName = "something";` rather than having to use the `this.set("propertyName", "something");` syntax.  The former has full intellisense support while the latter doesn't.
